name: Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    defaults:
      run:
        working-directory: ./front-end-app
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Manage NPM Dependencies
        uses: ./.github/actions/cache-node-dependencies
        with:
          app-name: "react-app"

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run ci:lint

      - name: Test
        run: npm run ci:test

      - name: SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: front-end-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase GitHub Actor
        id: lowercase_actor
        run: echo "ACTOR_LOWERCASE=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.ACTOR_LOWERCASE }}/ci-cd-example-front:latest

      - name: Install Netlify CLI
        run: npm install netlify-cli@17.10.1 -g

      - name: Deploy to Netlify
        run: |
          netlify deploy \
            --dir ./front-end-app/build \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }} \
            --prod